name: Deploy to staging

on:
    push:
        branches:
            - staging

jobs:
    deploy:
        name: Deploy to staging server
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy everything through SFTP
              uses: pressidium/lftp-deploy-action@v1
              with:
                  host: ${{ secrets.STAGING_SFTP_HOST }}
                  port: 22
                  username: ${{ secrets.STAGING_SFTP_USER }}
                  password: ${{ secrets.STAGING_SFTP_PASS }}
                  localDir: ./
                  remoteDir: /${{ secrets.STAGING_SFTP_DIR }}
                  delete: true
                  exclude: .git,node_modules,vendor,*.map,*.log,*.md,*.txt,*.json,*.yml,*.yaml,*.xml,*.zip,*.tar.gz,*.tgz,*.bak,*.swp,*.DS_Store,.env,.env.local,.env.development,.env.production,.env.staging
